version: '3.8'

services:
  encodelabs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encodelabs-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - encodelabs-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080/api/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  encodelabs-network:
    driver: bridge

volumes:
  logs:
    driver: local
