services:
  encodelabs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encodelabs-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - encodelabs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/api/actuator/health"]
      interval: 10s
      timeout: 7s
      retries: 3
      start_period: 15s

  postman-tests:
    image: postman/newman:alpine
    container_name: postman-tests
    depends_on:
      encodelabs-api:
        condition: service_healthy
    volumes:
      - ./tests:/etc/newman
    working_dir: /etc/newman
    command: run Encodelabs-test.postman_collection.json --delay-request 500 --reporters cli
    networks:
      - encodelabs-network

networks:
  encodelabs-network:
    driver: bridge

volumes:
  logs:
    driver: local
